### PR TITLE
scan path

### LINKED ISSUE #2926: Include PATH env. variable when searching for external players
#### Operating System Version:

linux/ nixos 
#### Download date:

nwjs 119.0.6045.105

#### Expected Behaviour:

First description of the issue here https://discourse.nixos.org/t/no-sound-on-popcorntime/41095/3
I had issues with audio on some videos, checked the FAQ that mentioned it was possible due to some new library and the workaround 
was to use an alternative player (until then I had no idea you could use an external player, so that was a good news :) ). 

To my surprise, popcorntime could not find my VLC player even though it was in PATH.  I digged a bit in the source code and found out that the paths are hardcoded 
https://github.com/popcorn-official/popcorn-desktop/pull/2635/files#diff-ca1b95b1c36992d38e3a83b4278a881511a4b41b529f1ebff9edc07ef7435492L236
and I assume PATH is ignored ?

I am curious as to why popcorntime seemingly ignore $PATH and if this could be changed to just look at it and remove all those hardcoded path (if people really need a player not in PATH, it's easier for them to add wrap popcorntime with a shellscript that adds to PATH the path to their player).

NB: I had no idea about this software before and it's beautiful and really impressive. Kudos to the maintainers

### PR DESCRIPTION
**Pull request by ivan1986**
close #2926

### CODE REVIEW

**Comment by teto** [comment]
thanks ! and I think you should be abloe to remove some if not all the subsequent `addPath`

**Comment by ivan1986** [comment]
hm, ok, let's make it only for linux and maybe mac, because windows realy not use path

**Comment by merseyV** [comment]
>(@merseyV are you there?:)

I'm free!! ... test what?  :)

**Comment by ivan1986** [comment]
@merseyV do macos add applications in path?
how i understand `/Applications` is same as `Program Files` and not add to path, but maybe install over brew or same add to path, so need also add path to scan for example if install vlc on mplayer over brew

**Comment by merseyV** [comment]
>how i understand /Applications is same as Program Files

Yes /Applications is the default location for installing apps on a Mac .. like your Program Files on C drive?

**Comment by merseyV** [comment]
>this line in your /src/app/lib/device/ext-player.js cause any issues with startup?

Any particular version ... I've got so many!

**Edit:** 
Works ok with 0.5.0 Arm release?

**Comment by ivan1986** [comment]
@merseyV 
how look $PATH in macos? `echo $PATH`

in *nix all application executable files put in `/usr/bin` and you can run any app just type name in terminal
in windows you need make lnk file so no sense look in PATH (by default only system32)
how on mac? looks need add /Applications same as PF in win
but also you have brew for install soft from repos, and because it's came from bsd and linux i think it may works same way

so question if you install by brew some player as vlc or mpv where it put 
and does popcorn find it with and without this string

**Comment by merseyV** [comment]
>Any one of the 0.5.0 ones 

Works ok with 0.5.0 official release. Haven't got a new 0.85.0 version (deleted the previous ones).

**Comment by merseyV** [comment]
>but also you have brew for install soft, and because it's came from bsd and linux i think it may works same way

You would know better than me @ivan1986 ? I'm just a dumb Mac user! Last time tried to teach me Brew ... he gave up trying!! :D

**Comment by merseyV** [comment]
>can test it, incl vlc via brew install)

Only brew I'm doing atm has a ring-pull on it!! :D

**Comment by ivan1986** [comment]
@merseyV ok, if it merged and not broken, it's ok, maybe after release know some new

**Comment by ivan1986** [comment]
a, sorry, i'm not read doc

`https://brew.sh/`
```
$ ls -l bin
bin/wget -> ../Cellar/wget/1.16.1/bin/wget
```
so yes, need add and all players install by it will be found

**Pull request merged**
